create table aktion (id varchar(255) not null, version bigint not null, datum timestamp not null, class varchar(255) not null, chargen_nummer varchar(255), menge decimal(19,2), methode varchar(255), mittel varchar(255), sorte varchar(255), wassergehalt decimal(19,2), art varchar(255), anzahl integer, anzahl_kontrolltage integer, ausgebaute_waben integer, bemerkung varchar(4000), brut integer, brutwaben integer, drohnenbrut_geschnitten boolean, futterwaben integer, koenigin_gesehen boolean, mittelwaende integer, sanftmut integer, volksstaerke integer, wabensitz integer, primary key (id));
create table bienenstand (id varchar(255) not null, version bigint not null, name varchar(255) not null, standort varchar(255) not null, x decimal(19,2) not null, y decimal(19,2) not null, primary key (id));
create table bienenstand_bienenvolk (bienenstand_voelker_id varchar(255) not null, bienenvolk_id varchar(255));
create table bienenvolk (id varchar(255) not null, version bigint not null, erstellt timestamp not null, koenigin_id varchar(255) not null, name varchar(255) not null, primary key (id));
create table koenigin (id varchar(255) not null, version bigint not null, geburtsjahr integer not null, primary key (id));
create table sec_role (id varchar(255) not null, version bigint not null, authority varchar(255) not null, primary key (id));
create table sec_user (id varchar(255) not null, version bigint not null, account_expired boolean not null, account_locked boolean not null, enabled boolean not null, "password" varchar(255) not null, password_expired boolean not null, username varchar(255) not null, primary key (id));
create table sec_userrole (user_id varchar(255) not null, role_id varchar(255) not null, primary key (user_id, role_id));
alter table sec_role add constraint UK_oah023x2ltqw09mdue7w0mcxb unique (authority);
alter table sec_user add constraint UK_5ctbdrlf3eismye20vsdtk8w8 unique (username);
alter table bienenstand_bienenvolk add constraint FK18ns9v5weeh0n6rimoi4fwtum foreign key (bienenvolk_id) references bienenvolk;
alter table bienenstand_bienenvolk add constraint FKf8vxsrb9f9w7kx0lju5e7winh foreign key (bienenstand_voelker_id) references bienenstand;
alter table bienenvolk add constraint FKm7jley1hwaosb8q05r4xj4pse foreign key (koenigin_id) references koenigin;
alter table sec_userrole add constraint FKg1dcqd7a0imwfbbt73ad2iqna foreign key (user_id) references sec_user;
alter table sec_userrole add constraint FKo0did7mtfullggl6ujfuufc3p foreign key (role_id) references sec_role;
